#ifndef SIMPLE_STATEMENT_TYPE_H
#define SIMPLE_STATEMENT_TYPE_H

enum SimpleStatementType
{
    UNDEFINED,
    BLOCK_DECLARATION_VARIABLE,
    SELECTION_STATEMENT,
    EXPRESSION_STATEMENT,
    USELESS_STATEMENT,
    RETURN_STATEMENT,
    DECLARATION_VARIABLE_STATEMENT,
    ITERATION_STATEMENT
};

#endif
