#ifndef _TOKEN_H
#define _TOKEN_H

enum TOKEN {
     TOKEN_ELLIPSE ,
     TOKEN_VOID ,
     TOKEN_LEFT_DEC_ASSIGN ,
     TOKEN_RIGHT_DEC_ASSIGN ,
     TOKEN_PLUS_ASSIGN ,
     TOKEN_MINUS_ASSIGN ,
     TOKEN_DIV_ASSIGN ,
     TOKEN_MUL_ASSIGN ,
     TOKEN_MOD_ASSIGN ,
     TOKEN_AND_ASSIGN ,
     TOKEN_OR_ASSIGN ,
     TOKEN_OR_EXCL_ASSIGN ,
     TOKEN_RIGHT_DEC ,
     TOKEN_LEFT_DEC ,
     TOKEN_MORE_THAN ,
     TOKEN_LESS_THAN ,
     TOKEN_DIFF ,
     TOKEN_EQUAL ,
     TOKEN_AND ,
     TOKEN_OR ,
     TOKEN_INCREMENT ,
     TOKEN_DECREMENT ,
     TOKEN_CHAR ,
     TOKEN_INT32 ,
     TOKEN_INT64 ,
     TOKEN_BREAK ,
     TOKEN_RETURN ,
     TOKEN_CONTINUE ,
     TOKEN_WHILE ,
     TOKEN_FOR ,
     TOKEN_IF ,
     TOKEN_ELSE ,
     TOKEN_ID ,
     TOKEN_INT ,
     TOKEN_NEG
};

#endif